-- Active: 1702464302277@@localhost@5000@Stream@public
-- Inserting data into the "actor" table
INSERT INTO actor (first_name, last_name, birth_date)
VALUES ('John', 'Doe', '1990-05-15'),
       ('Alice', 'Smith', '1985-08-22'),
       ('Bob', 'Johnson', '1978-03-10'),
       ('Eva', 'Brown', '1995-11-27'),
       ('Michael', 'Williams', '1980-06-18');


-- Path: public.sql
-- Inserting data into the "director" table
INSERT INTO director (first_name, last_name)
VALUES ('Christopher', 'Nolan'),
       ('Quentin', 'Tarantino'),
       ('Steven', 'Spielberg'),
       ('Greta', 'Gerwig'),
       ('Martin', 'Scorsese');


-- Path: public.sql
-- Inserting data into the "movie" table
INSERT INTO movie (title, duration, release_date)
VALUES ('Inception', 148, '2010-07-16'),
       ('Pulp Fiction', 154, '1994-10-14'),
       ('The Shawshank Redemption', 142, '1994-09-23'),
       ('Little Women', 135, '2019-12-25'),
       ('Goodfellas', 146, '1990-09-19');


-- Path: public.sql 
-- Inserting data into the "user" table
INSERT INTO "user" (email, password)
VALUES ('user1@example.com', 'password1'),
       ('user2@example.com', 'password2'),
       ('user3@example.com', 'password3'),
       ('user4@example.com', 'password4'),
       ('user5@example.com', 'password5');


-- Insérer des films préférés pour l'utilisateur avec user_id = 1
INSERT INTO favorite_movies (user_id, movie_id)
VALUES
    (1, 1),  -- Film avec movie_id = 1
    (1, 3),  -- Film avec movie_id = 3
    (1, 5);  -- Film avec movie_id = 5



-- DATA 2
-- Actors
-- Generated by the database client.
INSERT INTO actor (first_name, last_name, birth_date)
VALUES
  ('John', 'Doe', '1990-05-15'),
  ('Alice', 'Johnson', '1985-08-22'),
  ('Michael', 'Smith', '1982-03-10'),
  ('Emily', 'Brown', '1995-12-05'),
  ('David', 'Miller', '1992-09-18'),
  ('Sophia', 'Anderson', '1988-07-30'),
  ('Daniel', 'Taylor', '1980-11-25'),
  ('Olivia', 'Clark', '1998-02-14'),
  ('Matthew', 'Wilson', '1983-06-08'),
  ('Emma', 'Moore', '1991-04-03'),
  ('James', 'Johnson', '1987-01-20'),
  ('Ava', 'Williams', '1994-10-12'),
  ('William', 'Jones', '1986-07-02'),
  ('Isabella', 'Brown', '1981-09-28'),
  ('Liam', 'Davis', '1993-03-15');

--   Directors
-- Generated by the database client.
INSERT INTO director (first_name, last_name)
VALUES
  ('Ava', 'DuVernay'),
  ('Denis', 'Villeneuve'),
  ('Bong', 'Joon-ho'),
  ('Sofia', 'Coppola'),
  ('Alfonso', 'Cuarón');

-- Users
-- Generated by the database client.
INSERT INTO "user" (email, password)
VALUES
  ('user1@example.com', 'hashed_password_1'),
  ('user2@example.com', 'hashed_password_2'),
  ('user3@example.com', 'hashed_password_3'),
  ('user4@example.com', 'hashed_password_4'),
  ('user5@example.com', 'hashed_password_5'),
  ('user6@example.com', 'hashed_password_6'),
  ('user7@example.com', 'hashed_password_7'),
  ('user8@example.com', 'hashed_password_8'),
  ('user9@example.com', 'hashed_password_9'),
  ('user10@example.com', 'hashed_password_10'),
  ('user11@example.com', 'hashed_password_11'),
  ('user12@example.com', 'hashed_password_12'),
  ('user13@example.com', 'hashed_password_13'),
  ('user14@example.com', 'hashed_password_14'),
  ('user15@example.com', 'hashed_password_15'),
  ('user16@example.com', 'hashed_password_16'),
  ('user17@example.com', 'hashed_password_17'),
  ('user18@example.com', 'hashed_password_18'),
  ('user19@example.com', 'hashed_password_19'),
  ('user20@example.com', 'hashed_password_20'),
  ('user21@example.com', 'hashed_password_21'),
  ('user22@example.com', 'hashed_password_22'),
  ('user23@example.com', 'hashed_password_23'),
  ('user24@example.com', 'hashed_password_24'),
  ('user25@example.com', 'hashed_password_25'),
  ('user26@example.com', 'hashed_password_26'),
  ('user27@example.com', 'hashed_password_27'),
  ('user28@example.com', 'hashed_password_28'),
  ('user29@example.com', 'hashed_password_29'),
  ('user30@example.com', 'hashed_password_30');

-- Favorite Movies 

-- Generated by the database client.
-- Generated by the database client.-- Generated by the database client.
INSERT INTO favorite_movies (user_id, movie_id)
SELECT
  user_id,
  FLOOR(RANDOM() * (SELECT COUNT(*) FROM movie) + 1)
FROM
  "user"
CROSS JOIN
  generate_series(1, 35)
ON CONFLICT (user_id, movie_id) DO NOTHING;


-- Generated by the database client.
INSERT INTO movie (title, duration, release_date)
VALUES
  ('The Dark Knight', 152, '2008-07-18'),
  ('Fight Club', 139, '1999-10-15'),
  ('Forrest Gump', 142, '1994-07-06'),
  ('The Matrix', 136, '1999-03-31'),
  ('The Godfather', 175, '1972-03-24'),
  ('The Social Network', 120, '2010-09-24'),
  ('Eternal Sunshine of the Spotless Mind', 108, '2004-03-19'),
  ('The Silence of the Lambs', 118, '1991-02-14'),
  ('The Grand Budapest Hotel', 99, '2014-03-07'),
  ('Blade Runner', 117, '1982-06-25'),
  ('The Lord of the Rings: The Fellowship of the Ring', 178, '2001-12-19'),
  ('Casablanca', 102, '1942-11-26'),
  ('The Shining', 144, '1980-05-23'),
  ('Inglourious Basterds', 153, '2009-08-21'),
  ('Whiplash', 106, '2014-10-10'),
  ('The Great Gatsby', 143, '2013-05-10'),
  ('Jurassic Park', 127, '1993-06-11'),
  ('The Usual Suspects', 106, '1995-08-16'),
  ('Gone with the Wind', 238, '1939-12-15'),
  ('The Big Lebowski', 117, '1998-03-06'),
  ('American Beauty', 122, '1999-09-08'),
  ('Raiders of the Lost Ark', 115, '1981-06-12'),
  ('Citizen Kane', 119, '1941-05-01'),
  ('Avatar', 162, '2009-12-18'),
  ('The Pianist', 150, '2002-09-24'),
  ('Schindler''s List', 195, '1993-11-30'),
  ('A Clockwork Orange', 136, '1971-12-19'),
  ('The Departed', 151, '2006-10-06'),
  ('Memento', 113, '2000-10-11'),
  ('The Wizard of Oz', 102, '1939-08-25');

-- Movies and actors
-- Generated by the database client.
-- Generated by the database client.
INSERT INTO movie_actors (movie_id, actor_id, role)
SELECT
  FLOOR(RANDOM() * 35) + 1,
  FLOOR(RANDOM() * 20) + 1,
  'Role in Movie'
FROM
  generate_series(1, 700)
ON CONFLICT (movie_id, actor_id) DO NOTHING;
