-- Generated by the database client.
CREATE TABLE actor(
    actor_id SERIAL NOT NULL,
    first_name varchar(255),
    last_name varchar(255),
    birth_date date NOT NULL,
    PRIMARY KEY(actor_id)
);
COMMENT ON COLUMN actor.first_name IS 'This is a column for actor first names';
COMMENT ON COLUMN actor.last_name IS 'This is a column for actor last names';