-- Generated by the database client.
CREATE TABLE favorite_movies(
    user_id integer NOT NULL,
    movie_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    PRIMARY KEY(user_id,movie_id),
    CONSTRAINT favorite_movies_user_id_fkey FOREIGN key(user_id) REFERENCES "user"(user_id),
    CONSTRAINT favorite_movies_movie_id_fkey FOREIGN key(movie_id) REFERENCES movie(movie_id)
);
COMMENT ON TABLE "favorite_movies" IS 'Table de liaison pour les films préférés des utilisateurs';