-- Generated by the database client.
CREATE TABLE movie(
    movie_id SERIAL NOT NULL,
    title varchar(255),
    duration integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(movie_id)
);
COMMENT ON COLUMN movie.title IS 'This is a column for movie titles';
COMMENT ON COLUMN movie.duration IS 'This is a column for movie durations';
COMMENT ON COLUMN movie.created_at IS 'This is a column for movie created at';
COMMENT ON COLUMN movie.updated_at IS 'This is a column for movie updated at';
